name: GA Sheet Updater (hourly)

on:
  schedule:
    - cron: '0 * * * *'   # 매시간 정각(UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-api-python-client beautifulsoup4

      - name: Run
        run: python path/to/your_script.py
