name: Newsletter Scraper

on:
  schedule:
    - cron: '0 * * * *'   # 매시간 00분(UTC) = KST 매시 정각+9h
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create token file from secret
        run: echo '${{ secrets.GA_TOKEN_JSON }}' > token.json

      - name: Run scraper
        env:
          GITHUB_ACTIONS: true
        run: python newsletter_scraper.py
